# Generated by Django 3.2.9 on 2022-03-17 17:38

import alemeno.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kid_name', models.CharField(max_length=200)),
                ('kid_age', models.PositiveSmallIntegerField()),
                ('parent_phone', models.CharField(max_length=10)),
                ('parent_email', alemeno.models.LowercaseEmailField(max_length=254, unique=True, verbose_name='email address')),
            ],
            options={
                'verbose_name': 'Kid',
                'verbose_name_plural': 'kids',
                'db_table': 'kid_table',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField()),
                ('food_group', models.CharField(choices=[('Fruit', 'Fruit'), ('Vegetable', 'Vegetable'), ('Grain', 'Grain'), ('Protein', 'Protein'), ('Dairy', 'Dairy'), ('Unknown', 'Unknown')], max_length=50, verbose_name='Group')),
                ('approved_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alemeno.kid')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'db_table': 'image_table',
                'managed': True,
            },
        ),
    ]
